http {
	server {
		listen 127.0.0.1:8080;
		listen 8081;
		server_name webserv.com;
		root ./website;
		index index.html;
		autoindex off;
		error_page 400 /errors/error400.html;
		error_page 403 /errors/error403.html;
		error_page 404 /errors/error404.html;
		error_page 500 /errors/error500.html;
		error_page 502 /errors/error502.html;

		location / {
			autoindex off;
			limit_except GET POST;
		}

		location /forms {
			autoindex on;
			limit_except GET POST;
		}

		location /uploads {
			autoindex on;
			limit_except GET POST DELETE;
		}
	}

	server {
		listen 127.0.0.1:8080;
		listen 8083;
		server_name webserv2.com;
		root ./website2;
		index index.html;
		autoindex on;
		error_page 400 /errors/error400.html;
		error_page 403 /errors/error403.html;
		error_page 404 /errors/error404.html;
		error_page 500 /errors/error500.html;
		error_page 502 /errors/error502.html;

		location / {
			autoindex off;
			limit_except GET;
		}
	}
}
