http {
	server {
		listen 127.0.0.1:8080;
		server_name webserv.com;
		root ../website;
		index index.html;
		autoindex off;

		location / {
			root ../website;
			autoindex off;
			limit_except GET {
				deny all;
			}
		}

		location /forms {
			root ./website/forms;
			autoindex on;

			limit_except GET POST {
				deny all;
			}
		}

		location /uploads {
			root ./website/uploads;
			autoindex on;

			limit_except POST {
				deny all;
			}
		}

		location /cgi-bin {
			root ./cgi-bin;
			autoindex off;
			cgi_extension .py;
			cgi_path /usr/bin/python3;

			limit_except GET POST {
				deny all;
			}
		}

	}
}
